name: Notify
description: Notify when build success

inputs:
  image_name:
    description: "Affected projects"

runs:
  using: "composite"
  steps:
  - name: Discord notification
    env:
      DISCORD_WEBHOOK: ${{ env.DISCORD_WEBHOOK }}
      DISCORD_USERNAME: Phuong Anh Le
      DISCORD_AVATAR: https://media1.nguoiduatin.vn/m24/upload/4-2022/images/2022-10-31/lephuonganh9-1667200915-17-width650height867.jpg
    uses: Ilshidur/action-discord@master
    with:
      args: "Has a updated for ${{ inputs.image_name }}"