name: Docker Hub - Building
description: for building

inputs:
  docker_username:
    description: "Docker username"
    required: true
  docker_password:
    description: "Docker password"
    required: true
  target_build:
    description: "Target build"
    required: true
  # docker_file:
  #   description: "Docker file"
  #   required: false

outputs:
  image_name:
    description: "Image name"
    value: ${{ steps.dist.outputs.image_name }}

runs:
  using: "composite"
  steps:
  - name: Login to DockerHub
    uses: docker/login-action@v1 
    with:
      username: ${{ inputs.docker_username }}
      password: ${{ inputs.docker_password }}
  
  - name: Docker meta
    id: meta
    uses: docker/metadata-action@v5
    with:
      tags: |
        type=sha,enable=true,priority=100,prefix=sha-,suffix=,format=short

  - name: Set image name
    shell: bash
    id: dist
    run: |
      echo "image_name=${{inputs.docker_username}}/${{ inputs.target_build }}:${{ steps.meta.outputs.tags }}" >> $GITHUB_OUTPUT
    
  - name: Build Docker images
    shell: bash
    run: npx nx build:docker ${{ inputs.target_build }} --args="--IMAGE_HOST=${{ inputs.docker_username }} --IMAGE_TAG=${{ steps.meta.outputs.tags }}"
  
  # - name: Build and push Docker image
  #   uses: docker/build-push-action@v5
  #   id: dist
  #   with:
  #     context: ${{ inputs.docker_file }}
  #     push: true
  #     tags: ${{ steps.name.outputs.image_name }}

  