name: ga-setup-project
description: customize for setting up node

runs:
  using: "composite"
  steps:
  - uses: actions/setup-node@v2
    with:
      node-version: '22'
  
  - uses: actions/cache@v3
    id: modules-cache
    with:
      path: ./node_modules
      key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      restore-keys: |
        ${{ runner.os }}-yarn-
  
  - name: Install dependencies
    if: steps.modules-cache.outputs.cache-hit != 'true'
    shell: bash
    run: yarn install --frozen-lockfile
